### ISSUE TITLE
option for an IP whitelist or bind to localhost

### ISSUE THREAD

**Issue by FrostBird347** [wefhy/WhyMap#3]
An option to bind the webserver to localhost or block incoming connections to a whitelist would be great

**Comment by wefhy** [comment]
Will do within a week! I've been planning this for a while but I wanted to do some config support so that it's actually user switchable from the game

**Comment by wefhy** [comment]
Next release (1.5.0 in 2-3 days) will have a config file in `minecraft/WhyMap/config.toml`. You can change between a few options. Default settings allow only connection from localhost and look like this:

```toml
configFileVersion = 1

[userSettings]
    exposeHttpApi = "LOCALHOST_ONLY"
    minimapPosition = "TOP_LEFT"
    minimapMode = "DISABLED"

# exposeHttpApi: DISABLED, LOCALHOST_ONLY, EVERYWHERE, DEBUG
# minimapPosition: TOP_LEFT, TOP_CENTER, TOP_RIGHT
# minimapMode: DISABLED, NORTH_LOCKED, ROTATED
```

Better whitelisting will come some day, I hope this will suffice for the time being!
